version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - 'pr: dependencies'
    groups:
      stylelint-actions:
        patterns: ['stylelint/.github/*']
    cooldown:
      exclude: ['stylelint/.github/*']
