name: Lint Awesome List

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: npx awesome-lint
